name: dbt Config

on:
  push:
    branches: [main]
  pull_request:
    branches: [main] 
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch: 

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_HOST: ${{ secrets.DBT_HOST }}
      DBT_DB: ${{ secrets.DBT_DB }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DBT_PORT: ${{ secrets.DBT_PORT }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up node (for netlify CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dbt + dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dbt-core.txt
          pip install dbt-core==1.7.9 dbt-postgres==1.7.9 
          npm install -g netlify-cli


      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          first_personal_project:
            target: cloud
            outputs:
              dev:
                type: postgres
                threads: 1
                host: $DBT_HOST
                port: $DBT_PORT
                user: $DBT_USER
                password: $DBT_PASSWORD
                dbname: $DBT_DB
                schema: $DBT_SCHEMA
          EOF
      
      - name: Run dbt deps
        run: dbt deps   

      - name: Run dbt build
        shell: bash
        run: |
          set -euo pipefail
          dbt build 2>&1 | tee dbt_build.log

      - name: Run dbt test
        shell: bash
        # Run dbt tests and save output to a log file
        run: |
          set -euo pipefail
          dbt test 2>&1 | tee dbt_test.log

      - name: Generate dbt docs
        shell: bash
        run: |
          set -euo pipefail
          dbt docs generate

      - name: deploy dbt docs to netlify
        if: success()
        run: |
          netlify deploy --prod --dir=target --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.SITE_ID }}
          

      - name: Upload dbt logs and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-logs
          path: |
            dbt_build.log
            dbt_test.log
            target/
          
      - name: Slack notification
        if: always()
        continue-on-error: true
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, commit, author, message
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
